#!/usr/bin/env zsh

#
# iTerm only utilities
#


[ ! -n "$ITERM_PROFILE" ] && exit

local colors=(green yellow red magenta blue white grey)


function set_tab_color_rgb() {
  echo -n "\033]6;1;bg;red;brightness;$1\a"
  echo -n "\033]6;1;bg;green;brightness;$2\a"
  echo -n "\033]6;1;bg;blue;brightness;$3\a"
}

function reset_tab_color() {
  unset __SHA1N_PROFILE_TABCOLOR
  echo -n "\033]6;1;bg;*;default\a"
}

function set_tab_color() {
  local color=$(echo "${1}" | xargs)

  case $color in
  green)
    set_tab_color_rgb 178 204 8
    ;;

  yellow)
    set_tab_color_rgb 242 184 5
    ;;

  red)
    set_tab_color_rgb 239 79 13
    ;;

  magenta)
    set_tab_color_rgb 246 16 127
    ;;

  blue)
    set_tab_color_rgb 63 176 255
    ;;

  white)
    set_tab_color_rgb 250 247 239
    ;;

  grey)
    set_tab_color_rgb 83 94 97
    ;;

  default)
    reset_tab_color
    ;;

  *)
    if (($colors[(Ie)$__SHA1N_PROFILE_TABCOLOR])); then
      color="$__SHA1N_PROFILE_TABCOLOR"
    else
      color=default
    fi
    set_tab_color $color
  esac

  export __SHA1N_PROFILE_TABCOLOR="$color"
 }
