#!/usr/bin/env bash

# remove exited/created containers
containers=$(docker ps -aqf status=exited -f status=created)
[ -n "$containers" ] && docker rm -vf $containers

# remove untagged images
images=$(docker images -qf dangling=true)
[ -n "$images" ] && docker rmi $images

# remove unused volumes
docker volume prune -f
