#!/usr/bin/env zsh

zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*' special-dirs true
zstyle ':completion:*:default' list-colors \
  "di=1;36" "ln=1;35" "so=32" "pi=33" "ex=31" "bd=34;46" "cd=34;43" \
  "su=30;41" "sg=30;46" "tw=30;42" "ow=30;43"

autoload -U compinit
if [[ -n ~/.zcompdump(#qN.mh+24) ]] || [[ ! -f ~/.zcompdump ]]; then
  compinit
else
  compinit -C
fi
autoload -U +X bashcompinit && bashcompinit
