#!/usr/bin/env zsh

export CODE="$HOME/code"
export NVM_DIR="$HOME/.nvm"
export GO111MODULE=on

# enable ls colors
export CLICOLOR=1
# ls
export LSCOLORS=GxFxCxDxBxegedabagaced
# grep
export GREP_COLOR='1;35;40'

PATH="$PATH:$HOME/.local/bin:$HOME/go/bin:$SHA1N_PROFILE_HOME/scripts"

# Backup
export BACKUP_DST_PATH="/Volumes/Backup/latest"
export BACKUP_SRC_PATH="/Volumes/Content"

# pytest
export PYTEST_ADDOPTS='-r=fE --maxfail=1 --no-header --failed-first --durations=5 -vv'
# python cache directories location
export PYTHONPYCACHEPREFIX="${HOME}/.cache/Python"
