#!/usr/bin/env zsh

# history-substring-search key bindings are deferred in load.zsh
# (they depend on the zsh-history-substring-search plugin which is also deferred)

# line navigation
bindkey  "^[[H"   beginning-of-line
bindkey  "^[[F"   end-of-line
bindkey  "^[[3~"  delete-char
# completion
bindkey '^I' complete-word
