name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"

jobs:
  main:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0 

      - name: Install Zsh
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install zsh

      - name: Zsh Version
        run: zsh --version

      - name: Update Submodules
        run: make update_submodules

      - name: Run Tests
        run: make test
